; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; uncomment this line to build on Macbook local dir instead of NFS mount
workspace_dir = /var/tmp/garmin-build

[env]
platform = espressif32@6.3.2
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32doit-devkit-v1
framework = arduino
upload_speed = 460800
monitor_speed = 115200
monitor_filters =
	; esp32_exception_decoder  ; Comment out for size optimization
	; log2file                 ; Comment out for size optimization
build_type = release
board_build.partitions = medspiffs.csv
board_build.embed_txtfiles = sdkconfig.defaults
build_flags =
	-Os
	-ffunction-sections
	-fdata-sections
	-Wl,--gc-sections
	-DNDEBUG
	-D ELEGANTOTA
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
;	-D NTP
;	-D DEEPSLEEP
;	-D TEMPLATE
	-DCONFIG_ESP_SYSTEM_PANIC_SILENT_REBOOT=1
lib_compat_mode = strict
lib_ldf_mode = chain+
lib_deps = 
	https://github.com/ESP32Async/AsyncTCP#v3.4.9
	https://github.com/ESP32Async/ESPAsyncWebServer#v3.8.1
	https://github.com/ayushsharma82/ElegantOTA
;	https://github.com/ayushsharma82/WebSerial
;	Macbook
	/Users/wjquigs/Dropbox/ESP/WebSerialPro-Essential-Bundle-v2-1-0.zip
;	/srv/nfs/shared/ESP/WebSerialPro-Essential-Bundle-v2-1-0.zip
;	build-server-ts (graviton)
;	/home/wjquigs/nfs/ESP/WebSerialPro-Essential-Bundle-v2-1-0.zip
	bblanchon/ArduinoJson@^7.2.0
;	mairas/ReactESP@^2.0.0
	adafruit/Adafruit BME280 Library@^2.2.4
	adafruit/Adafruit SSD1306@2.5.11
	adafruit/Adafruit ADS1X15@2.5.0
	pfeerick/elapsedMillis@1.0.6
	https://github.com/wjquigs11/movingAvg
	ttlappalainen/NMEA2000_mcp
	https://github.com/ttlappalainen/CAN_BUS_Shield.git
	ttlappalainen/NMEA2000-library@4.21.5
;	ttlappalainen/NMEA2000_mcp
	ttlappalainen/NMEA2000_esp32
	https://github.com/wjquigs11/NMEA0183
	adafruit/Adafruit BNO08x@1.2.5
;	https://github.com/pierremolinaro/acan-esp32
;	https://github.com/Seeed-Studio/Seeed_Arduino_CAN

[env:tatiana]
extends = env:main-bus
;monitor_port = /dev/cu.usbserial-0001
;upload_port = /dev/cu.usbserial-0001
lib_compat_mode = soft
build_flags =
	-D WEBSERIAL
	-D APPHANDLER
	-D WIFI
	-D HONEY
	-D RTK
	-D RTK_HYBRID
	-D N2K
	-D NMEA0183
	-D BNO08X
	-D BNOADDR=0x4A
	-D DISPLAYON
	-D TCP_FORWARD
	-D SEATALK
;	-D AIS_FORWARD
;	-D MOB_PING
;   -D TACK
	${env.build_flags}
lib_deps = 
	${env.lib_deps}
;	https://github.com/plerup/espsoftwareserial

; ceratops currently has a dual isolated CAN bus adapter
; waveshare
; it might be bad because it's not seeing traffic on either bus
; will debug if Paul wants to re-try rotation correction
[env:ceratops]
extends = env:main-bus
;monitor_port = /dev/cu.usbserial-0001
;upload_port = /dev/cu.usbserial-0001
lib_compat_mode = soft
build_flags =
	-D WEBSERIAL
	-D APPHANDLER
	-D WIFI
	-D N2K
	-D BNO08X
	-D BNOADDR=0x4B
	-D DISPLAYON
	${env.build_flags}
lib_deps = 
	${env.lib_deps}